photosoc/urls.py
from django.conf.urls.defaults import *
from photosoc_app.views import *
from django.views.generic import TemplateView
import os

site_media=os.path.join(os.path.dirname(__file__), 'site_media')

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^$', main_page),
	(r'^users/$', users_page),
	(r'^login/$', 'django.contrib.auth.views.login'),
	(r'^logout/$', logout_page),
	(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': site_media}),
    (r'^register/$', register_page),
    (r'^register/success/$', TemplateView.as_view(template_name='registration/register_success.html')),
    (r'^users/(?P<uname>\w+)/$', user_page),
    (r'^photos/$', photos_page),
    (r'^photos/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/debellatrix/Desktop/photosoc'}),
    (r'^admin/', include(admin.site.urls)),
    (r'^upload/$', upload_photo),
    (r'^friends/$', friends_page),
    (r'^friend/add/$', friend_add),
    (r'^like/$', like_photo_page),
    (r'^unlike/$', unlike_photo_page),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^photo/(?P<photo_id>\d+)/comments/$', photo_comments_page),
    (r'^photo/(?P<photo_id>\d+)/tag/$', tag_photo_page),
    # Examples:
    # url(r'^$', 'photosoc.views.home', name='home'),
    # url(r'^photosoc/', include('photosoc.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    (r'^', include('photosoc_app.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photosoc_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files import File


class Photo(models.Model):
	user=models.ForeignKey(User)
	photo=models.ImageField(upload_to='uploaded_photos/',blank=True,null=True)
	caption=models.CharField(max_length=200)
	pub_date=models.DateTimeField(auto_now_add=True)
	private=models.BooleanField() 
	likes=models.IntegerField(default=0)
	likers=models.ManyToManyField(User, related_name='likers')
	
	def __unicode__(self):
		return self.caption
	
	
class Tag(models.Model):
	name=models.CharField(max_length=100)
	photo=models.ManyToManyField(Photo)
	
	def __unicode__(self):
		return self.name
	
	
class Friendship(models.Model):
	from_friend=models.ForeignKey(
		User, related_name='friend_set'
		)
	to_friend=models.ForeignKey(
		User, related_name='to_friend_set'
		)
		
	def __unicode__(self):
		return u'%s, %s' % (self.from_friend.username, self.to_friend.username)
			
	class Meta:
		unique_together=(('to_friend', 'from_friend'), )

photosoc/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<link rel="stylesheet" href="/site_media/style.css" type="text/css" />
<title>
Photosoc | {% block title %}{% endblock %}
</title>
</head>
<body>
<div id="nav">
	<a href="/">home</a> |
	{% if user.is_authenticated %}
	<a href="/users/{{ user.username }}">{{ user.first_name }} {{ user.last_name }}</a> |
	<a href="/upload/">upload photos</a> |
	<a href="/logout">logout</a>
	{% else %}
	<a href="/login/">login</a> |
	<a href="/register/">register</a>
	{% endif %}
</div>
<br><h1>{% block head %}{% endblock %}</h1>
{% block content %}{% endblock %}
</body>
</html>

photosoc/templates/friends_page.html
{% extends "base.html" %}
{% block title %}Friends{% endblock %}
{% block head %}{{ user.first_name }} {{ user.last_name }}'s friends{% endblock %}
{% block content %}
{% if friends %}
	<ul>
	{% for friend in friends %}
	<li><a href="/users/{{friend.username}}/">{{ friend.first_name }} {{ friend.last_name }}</a></li>
	{% endfor %}
	</ul>
	{% else %}
	<p>No friends found.</p>
{% endif %}
{% endblock %}

photosoc/templates/main_page.html
{% extends "base.html" %}
{% block title %}Welcome to Photosoc{% endblock %}
{% block head %}Welcome to Photosoc{% endblock %}
{% block content %}
{% if user.username %}
<p>Welcome, {{ user.username }}!
Here you can share your photos!</p>
<p><a href="/users/">List of Photosoc users</a></p>
<p><a href="/friends/">List of friends</p>
<p><a href="/photos/">Photo feed</p>
<p><a href="/upload/">Upload a photo</p>
{% else %}
<p>Welcome, anonymous user!
You need to <a href="/login/">login</a>
before you can share your photos.</p>
{% endif %}
{% endblock %}

photosoc/templates/photo_comments_page.html
{% extends "base.html" %}
{% load comments %}
{% block title %}{{ photo.caption }}{% endblock %}
{% block head %}{{ photo.caption }}{% endblock %}
{% block content %}
{% if photo %}
<p><img src="{{ photo.photo.url }}"/></p>
<p>Posted by {{ photo.user.first_name }} {{ photo.user.last_name }} on {{ photo.pub_date }}</p>
<h2>Comments</h2>
{% get_comment_list for photosoc_app.photo photo.id as comment_list %}
{% for comment in comment_list %}
<div class="comment">
<p><b>{{ comment.user.username }}</b> said:</p>
{{ comment.comment|escape|urlizetrunc:40|linebreaks }}
</div>
{% endfor %}
{% render_comment_form for photosoc_app.photo photo.id %}
{% endif %}
{% endblock %}

photosoc/templates/photos_page.html
{% extends "base.html" %}
{% block title %}Photos{% endblock %}
{% block head %}Photo feed{% endblock %}
{% block content %}
{% if photos %}
	<ul>
	{% for p in photos %}
		<p><img src="{{ p.photo.url }}"/></p>
		<p>Posted by {{ p.user.first_name }} {{ p.user.last_name }} on {{ p.pub_date }}<br>Caption: {{ p.caption }}<br>
		{% if p.private %}
			Privacy: Private<br>
		{% else %}
			Privacy: Public<br>
		{% endif %}
		Tagged: 
		{% for t in p.tag_set.all %}
				{{ t.name }} 
		{% endfor %}
		<br><a href="/photo/{{ p.id }}/tag/">Tag this photo</a>
		</p>
		{% if user in p.likers.all %}
			<a href="/unlike/?id={{ p.id }}">Unlike</a>
		{% else %}
			<a href="/like/?id={{ p.id }}">Like</a>
		{% endif %}
		<p>{{ p.likes }} likes<br>
		People who like this:
		{% for liker in p.likers.all %}
			{{ liker.first_name }} {{ liker.last_name }}
		{% endfor %}
		<br><a href="/photo/{{ p.id }}/comments/">Comments</a>
		</p>	
		<hr>
	{% endfor %}
	</ul>
	{% else %}
	<p>No photos found.</p>
{% endif %}
{% endblock %}

photosoc/templates/tag_page.html
{% extends "base.html" %}
{% block title %}Upload a photo{% endblock %}
{% block head %}Upload a photo{% endblock %}
{% block content %}
<form enctype="multipart/form-data" method="post" action=".">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="save" />
</form>
{% endblock %}

photosoc/templates/tag_photo_page.html
{% extends "base.html" %}
{% block title %}Tag a photo{% endblock %}
{% block head %}Tag a photo{% endblock %}
{% block content %}
<form method="post" action=".">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="save" />
</form>
{% endblock %}

photosoc/templates/upload_photo.html
{% extends "base.html" %}
{% block title %}Upload a photo{% endblock %}
{% block head %}Upload a photo{% endblock %}
{% block content %}
<form enctype="multipart/form-data" method="post" action=".">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="save" />
</form>
{% endblock %}

photosoc/templates/user_page.html
{% extends "base.html" %}
{% block title %}{{userr.first_name}} {{ userr.last_name }}{% endblock %}
{% block head %}{{userr.first_name}} {{ userr.last_name }}{% endblock %}
{% block content %}
{% ifnotequal userr.username logged_in_user.username %}
	{% if is_friend %}
	<p>{{userr.first_name}} {{ userr.last_name }} is a friend of yours.</p>
	{% else %}
	<a href="/friend/add/?username={{ userr.username }}">
	add {{userr.first_name}} {{ userr.last_name }} to your friends</a>
	{% endif %}
{% endifnotequal %}
{% if userr %}
	{% if friends %}
		<p>{{userr.first_name}}'s friends</p>
		<ul>
		{% for friend in friends %}
			<li><a href="/users/{{ friend.username }}/">{{ friend.first_name }} {{ friend.last_name }}</a></li>
			{% endfor %}	
		</ul>
	{% endif %}
	{% if photos %}
		<p>{{userr.first_name}}'s photos</p>
		<ul>
		{% for p in photos %}
			<p><img src="{{ p.photo.url }}"/></p>
		{% endfor %}
		</ul>
		{% else %}
		{% if is_friend %}
			<p>{{userr.first_name}} hasn't uploaded any photos yet.</p>
		{% else %}
			<p>{{userr.first_name}} doesn't have any public photos.</p>
		{% endif %}
	{% endif %}
{% endif %}
{% endblock %}

photosoc/templates/users_page.html
{% extends "base.html" %}
{% block title %}Users{% endblock %}
{% block head %}Photosoc users{% endblock %}
{% block content %}
{% if users %}
	<ul>
	{% for user in users %}
	<li><a href="/users/{{ user.username }}/">{{ user.first_name }} {{ user.last_name }}</a></li>
	{% endfor %}
	</ul>
	{% else %}
	<p>No users found.</p>
{% endif %}
{% endblock %}